### ISSUE TITLE
Error in plotPCA

### ISSUE THREAD

**Issue by dongjuleem** [MarioniLab/Aneuploidy2017#2]
Thank you for providing a good tool. 
I am reaching out because I encountered an error while processing my scRNA data using scploid.

```
> plotPCA(ploidytest, cols = random_colours)
Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x'
```

```
> sum(is.na(counts))
[1] 0
> sum(is.na(gene_table))
[1] 0
> sum(is.na(ploidytest@cpm))
[1] 326172
> 
```

It seems that the error occurred due to missing values in ploidytest@cpm, which was created using makeAneu. 
I would be very grateful if you could provide a solution or explain the cause.

**Comment by jonathangriffiths** [comment]
Hi there,

Please could you provide a reproducable example? That is, with the counts, gene_table files, and how you created the ploidytest object?

More importantly I think there are probably more reliable options for calling single cell ploidy these days than my old method. For example, [this paper](https://genome.cshlp.org/content/30/6/814.short) seemed to achieve better results than I was able to from the Petropoulos dataset (though that dataset has issues). I also saw at an ASHG that smoothing of the gene expression data (sometimes called "imputation") really made the results more robust.

I imagine there are even better versions that have been created since then, though.

Jonny

**Comment by dongjuleem** [comment]
Thank you so much for your quick and friendly response.🥹🥹🥹

First of all, the data I have is not based on full transcript reads, but rather on 10X genomics 3' end read data, which reads the 3’ ends of transcripts. Perhaps because of this, when I tried to follow the methods recommended in [the paper](https://genome.cshlp.org/content/30/6/814.short), no SNP candidates appeared in GATK's HaplotypeCaller, so I couldn’t proceed.

Next, I have created the ploidytest objects with the following code. 
One thing I modified was to keep only the ENSG genes.
(I'm not sure if that's okay..)

```
counts = read.table(
  paste0(fold, "/sample.txt"),
  header = T,
  row.names = 1
)

colnames(counts) = paste0("cell_", 1:ncol(counts))

# select ENSG gene
counts <- counts[grepl("^ENSG", rownames(counts)), ]

human_ensembl = useMart("ensembl")
human_ensembl = useDataset("hsapiens_gene_ensembl", 
                           mart = human_ensembl)

gene_table = getBM(
  attributes = c("ensembl_gene_id", "chromosome_name"),
  mart = human_ensembl,
  values = as.character(rownames(counts)),
  filters = "ensembl_gene_id"
)

gene_table = gene_table[gene_table$chromosome_name %in% 1:22, ]
counts = counts[gene_table$ensembl_gene_id, ]

ploidytest = makeAneu(counts = as.matrix(counts), 
                      genes = gene_table$ensembl_gene_id, 
                      chrs = gene_table$chromosome_name, 
                      cellNames = colnames(counts), 
                      cellGroups = rep("group_1", ncol(counts)))
```

**Comment by jonathangriffiths** [comment]
If the cpm slot is broken immediately after you've made the pbject, then I think the only lines that can be relevant are [these ones](https://github.com/MarioniLab/Aneuploidy2017/blob/286c064bce53ccd55c2d1a600abd12a84f655328/package/R/methods.R#L58)
```
cpm = sweep(counts*1e6,
              2,
              apply(counts, 2, sum),
              "/")
```

I would recommend you check your counts object after subsetting to ensure it has kept the data as it is meant to be, that the counts are not already log-transformed or similar, and that the column sums are large enough.

In the paper we did not recommend running the method on 10x data because they had too few molecules captured per cell. That might have changed as the technology has evolved but I am not so confident.
